name: build-release

on:
  push:
    branches: [ "**" ]

jobs:
  build_app_release:
    name: Build app release and upload assets
    runs-on: ubuntu-latest
    container:
      # image: novice/build:latest
      image: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set release tag env
        run: |
          BRANCH=${GITHUB_REF##*/}
          TAG="v1.0-$BRANCH"
          echo "TagName=$TAG" >> $GITHUB_ENV
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "::notice::TagName=$TAG"
      - name: Build app and zip it
        run: |
          # ./pack.sh ${{ env.BRANCH }}
          echo "hello world and BRANCH=$BRANCH" > test.txt
      - name: Upload linux build assets
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Auto build app for
            - macos_aarch64
            - macos_x64
            - linux_armv7
            - linux_aarch64
            - linux_x86_64
          # file: ${{ github.workspace }}/*.7z
          file: test.txt
          tag_name: ${{ env.TagName }}
          # overwrite: true
          # file_glob: true
