name: build-release

on:
  push:
    branches: [ "**" ]

jobs:
  build_app_release:
    name: Build app release and upload assets
    runs-on: ubuntu-latest
    container:
      image: novice/build:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set release tag env
        run: |
          BRANCH=${GITHUB_REF##*/}
          echo "TagName=v1.0-$BRANCH" >> $GITHUB_ENV
          echo "::notice::TagName=$TAG"
      - name: Build app and zip it
        run: ./pack.sh ${{ env.TagName }}
      - name: Upload linux build assets
        uses: svenstaro/upload-release-action@v2
        with:
          body: |
            Auto build app for
            - macos_aarch64
            - macos_x64
            - linux_armv7
            - linux_aarch64
            - linux_x86_64
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.7z
          tag: ${{ env.TagName }}
          overwrite: true
          file_glob: true
